// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/micro/examples/booking/api/hotel/proto/hotel.proto

/*
Package hotel is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/examples/booking/api/hotel/proto/hotel.proto

It has these top-level messages:
	Request
	Response
*/
package hotel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/micro/examples/booking/srv/profile/proto"
import _ "github.com/micro/examples/booking/srv/rate/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Hotel service

type HotelClient interface {
	Rates(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type hotelClient struct {
	c           client.Client
	serviceName string
}

func NewHotelClient(serviceName string, c client.Client) HotelClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "hotel"
	}
	return &hotelClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *hotelClient) Rates(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Hotel.Rates", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hotel service

type HotelHandler interface {
	Rates(context.Context, *Request, *Response) error
}

func RegisterHotelHandler(s server.Server, hdlr HotelHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Hotel{hdlr}, opts...))
}

type Hotel struct {
	HotelHandler
}

func (h *Hotel) Rates(ctx context.Context, in *Request, out *Response) error {
	return h.HotelHandler.Rates(ctx, in, out)
}
