// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/micro/examples/booking/srv/profile/proto/profile.proto

/*
Package profile is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/examples/booking/srv/profile/proto/profile.proto

It has these top-level messages:
	Request
	Result
	Hotel
	Address
	Image
*/
package profile

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Profile service

type ProfileClient interface {
	GetProfiles(ctx context.Context, in *Request, opts ...client.CallOption) (*Result, error)
}

type profileClient struct {
	c           client.Client
	serviceName string
}

func NewProfileClient(serviceName string, c client.Client) ProfileClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "profile"
	}
	return &profileClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *profileClient) GetProfiles(ctx context.Context, in *Request, opts ...client.CallOption) (*Result, error) {
	req := c.c.NewRequest(c.serviceName, "Profile.GetProfiles", in)
	out := new(Result)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Profile service

type ProfileHandler interface {
	GetProfiles(context.Context, *Request, *Result) error
}

func RegisterProfileHandler(s server.Server, hdlr ProfileHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Profile{hdlr}, opts...))
}

type Profile struct {
	ProfileHandler
}

func (h *Profile) GetProfiles(ctx context.Context, in *Request, out *Result) error {
	return h.ProfileHandler.GetProfiles(ctx, in, out)
}
